# Notes:
#
# Lint and test could be executed in parallel, but that would only make things slower.
# Other then that everything is sequentially dependent.
#
# By re-using a build command instead of requiring a build job before release
# we don't need to persist to a workspace which saves time.

version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:12.12.0-browsers

commands:
  npm_install:
    steps:
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            if [ -d node_modules ]; then
              echo "Dependencies restored from cache already"
            else
              npm install
            fi
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  build_and_test:
    steps:
      - checkout
      - npm_install
      - run: npm run build
      - run: npm run lint
      - run: npm test

jobs:
  build:
    executor: default
    steps:
      - build_and_test

  release:
    executor: default
    steps:
      - build_and_test
      # TODO: deploy website

workflows:
  version: 2.1

  build_or_release:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - release:
          filters:
            branches:
              only: master
